In [67]:
import torch

In [88]:
b=torch.rand(4)

In [89]:
print(b)

tensor([0.5889, 0.6694, 0.9554, 0.5468])


In [90]:
b>0.5

tensor([1, 1, 1, 1], dtype=torch.uint8)

In [68]:
#the number of entries in database
#num_entries = 5000

#db = torch.rand(num_entries) > 0.5
#db

how does torch.rand(num_entries) > 0.5 work?
torch.rand(num_entries) returns values between 0 and 1
> returns false(0) or true(1),  so see the example.

In [91]:
b=torch.rand(4)

In [92]:
print(b)

tensor([0.3769, 0.6688, 0.8658, 0.0407])


In [93]:
b>0.5

tensor([0, 1, 1, 0], dtype=torch.uint8)

In [69]:
i=0
databases= list()
num_entries = 5000
while i < 5000:
    db = torch.rand(num_entries) > 0.5
    db = torch.cat((db[0:i], db[i+1:]))
    databases.append(db)
    i+=1    

In [70]:
print(databases)

[tensor([1, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8), tensor([0, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8), tensor([1, 1, 1,  ..., 0, 1, 1], dtype=torch.uint8), tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8), tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8), tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8), tensor([0, 1, 1,  ..., 0, 1, 1], dtype=torch.uint8), tensor([0, 0, 0,  ..., 1, 0, 0], dtype=torch.uint8), tensor([0, 0, 1,  ..., 1, 1, 1], dtype=torch.uint8), tensor([0, 1, 0,  ..., 0, 0, 1], dtype=torch.uint8), tensor([1, 1, 0,  ..., 1, 0, 1], dtype=torch.uint8), tensor([1, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8), tensor([1, 0, 1,  ..., 0, 1, 1], dtype=torch.uint8), tensor([0, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8), tensor([1, 0, 1,  ..., 0, 0, 0], dtype=torch.uint8), tensor([1, 0, 1,  ..., 0, 0, 0], dtype=torch.uint8), tensor([1, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8), tensor([0, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8), tensor([1, 0, 0,  ..., 0, 0, 1], dtype=torch.

In [71]:
len(databases)

5000

In [72]:
len(databases[3])

4999

In [78]:
db1 = torch.rand(num_entries) > 0.5

In [79]:
def removeEntry(db, entry):
    return torch.cat((db1[0:entry], db1[entry+1:]))

In [80]:
parallel_databases = list()
for i in range(len(databases)):
    pdb = removeEntry(db, i)
    parallel_databases.append(pdb)
    

In [81]:
len(parallel_databases)

5000

In [82]:
len(parallel_databases[5])

4999