In [1]:
import torch

In [2]:
import numpy as np

In [3]:
#packged, lone standing function
def create_db_and_parallels2(num_entries):
    db = torch.rand(num_entries) > 0.5
    pdb = list()
    for i in range(len(db)):
        pdbs = torch.cat((db[0:i], db[i+1:]))
        pdb.append(pdbs)
    return db, pdb

In [4]:
def sum_query(db):
    return torch.sum(db)

In [5]:
def sum_query2(db):
    return db.sum()

In [6]:
np.random.seed(300)

In [13]:
def laplacian(db, query, sensitivity):
    epsilon = 0.5
    beta = sensitivity / epsilon
    noise = torch.tensor(np.random.laplace(0, beta, 1))
    
    return query(db) + noise

In [14]:
db, pdb = create_db_and_parallels2(100)

In [15]:
sum_query(db)

tensor(56)

In [16]:
sum_query(db)

tensor(56)

In [17]:
db

tensor([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 1, 1, 1], dtype=torch.uint8)

In [18]:
np.random.seed(300)
laplacian(db, sum_query, 1)

tensor([55.7943], dtype=torch.float64)

In [19]:
np.random.seed(300)
laplacian(db, sum_query, 1)

tensor([55.7943], dtype=torch.float64)

In [20]:
np.random.seed(300)
laplacian(db, sum_query2, 1)

tensor([55.7943], dtype=torch.float64)

In [21]:
def mean_query(db):
    return torch.mean(db.float())

In [22]:
laplacian(db, mean_query, 1)

tensor([-1.0727], dtype=torch.float64)

In [23]:
laplacian(db, mean_query, 1/100)

tensor([0.5539], dtype=torch.float64)

In [24]:
db

tensor([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 1, 1, 1], dtype=torch.uint8)

In [25]:
sum(db)

tensor(56, dtype=torch.uint8)

In [26]:
sum(db)

tensor(56, dtype=torch.uint8)

In [27]:
sum_query(db)

tensor(56)