In [17]:
import torch

In [34]:
import numpy as np

In [55]:
num_entries = 5000

In [59]:
torch.from_numpy(np.random.randint(low=0, high=2, size=num_entries))

tensor([1, 0, 1,  ..., 0, 0, 1])

In [18]:
def removeEntry(db, entry):
    return torch.cat((db[0:entry], db[entry+1:]))

In [19]:
def get_parallel_dbs(db):
    parallel_databases = list()
    for i in range(len(db)):
        pdb = removeEntry(db, i)
        parallel_databases.append(pdb)
    return parallel_databases

In [20]:
def create_db_and_parallels(num_entries):
    db = torch.rand(num_entries) > 0.5
    pdb = get_parallel_dbs(db)
    return db, pdb

In [21]:
db, pdb = create_db_and_parallels(20)

In [22]:
print(db,pdb)

tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8) [tensor([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8), tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
 

In [24]:
db

tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
       dtype=torch.uint8)

In [23]:
pdb

[tensor([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [25]:
def query(db):
    return torch.sum(db)

In [27]:
query(db)

tensor(13)

In [30]:
query(pdb[2])

tensor(12)

If sensitivity is zero, it would not matter who we remove

In [31]:
full_db_result = query(db)

In [32]:
max_distance = 0
for each in pdb:
    pdb_result = query(each)
    db_distance = torch.abs(pdb_result-full_db_result)
    if (db_distance>max_distance):
        max_distance = db_distance

In [33]:
max_distance

tensor(1)

Sensitivity - maximum amount that the query changes when removing an individual from database - L1