In [10]:
import numpy as np

In [11]:
num_teachers = 10 #working with 10 hospitals
num_examples = 10000 #size of dataset
num_labels = 10 #labels for our clasifier

In [12]:
preds = (np.random.rand(num_teachers, num_examples)*num_labels).astype(int) #fake labels

In [13]:
preds

array([[3, 9, 0, ..., 0, 9, 3],
       [6, 5, 9, ..., 1, 2, 6],
       [7, 5, 6, ..., 0, 3, 9],
       ...,
       [0, 8, 1, ..., 1, 2, 3],
       [0, 0, 9, ..., 0, 1, 1],
       [9, 2, 5, ..., 1, 6, 7]])

In [14]:
preds.shape

(10, 10000)

In [15]:
preds[0]

array([3, 9, 0, ..., 0, 9, 3])

In [16]:
an_image = preds[:, 0]

In [17]:
an_image

array([3, 6, 7, 2, 9, 5, 9, 0, 0, 9])

In [18]:
label_counts = np.bincount(an_image, minlength=num_labels)

In [19]:
epsilon = 0.1

In [20]:
beta = 1 / epsilon

In [21]:
for i in range(len(label_counts)):
    label_counts[i] += np.random.laplace(0, beta, 1)

In [22]:
label_counts

array([-12,  -7,  -3,   9, -12,   1,   3, -19,   7,  -4])

In [23]:
new_label = np.argmax(label_counts)

In [27]:
preds = (np.random.rand(num_teachers, num_examples)*num_labels).astype(int).transpose(1,0)

In [28]:
new_labels = list()
for an_image in preds:
    label_counts = np.bincount(an_image, minlength=num_labels)
    epsilon = 0.1
    beta = 1 / epsilon
    for i in range(len(label_counts)):
        label_counts[i] += np.random.laplace(0, beta, 1)
        
    new_label = np.argmax(label_counts)
    
    new_labels.append(new_label)       

In [29]:
len(new_labels)

10000